default:
  dec_sep: ','
  out_loc: Output/
  genotype_monitor: Configs/genotypes_per_monitor.xlsx
  day3_dates: Configs/day3_monitors.xlsx
  dead_threshold: {normal: 719, SRT: 599}
  WASO: {normal: 720, SRT: 600}
